name: Update Daily Birthdays

on:
  schedule:
    - cron: '5 8 * * *'   # 08:05 UTC daily (change as you like)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run birthday scraper
        run: python birthday_scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet; then
            git add docs/birthdays/*.html
            git commit -m "Update birthdays $(date -u +%F)"
            git push
          fi
