name: Update Daily Birthdays

on:
  schedule:
    - cron: "5 8 * * *"   # runs daily at 08:05 UTC (adjust if you prefer)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run birthday scraper
        run: |
          python birthday_scraper.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          # Stage ALL changes (including new/untracked files) under docs/birthdays
          git add -A docs/birthdays
          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update birthdays $(date -u +%F)"
            git push
          else
            echo "No changes to commit."
          fi
